const WMO_Weather_Codes = [
  { code: 0, text: "Clear sky" },
  { code: 1, text: "Mostly clear" },
  { code: 2, text: "Partly cloudy" },
  { code: 3, text: "Overcast" },
  { code: 45, text: "Fog" },
  { code: 48, text: "Depositing rime fog" },
  { code: 51, text: "Light drizzle" },
  { code: 53, text: "Moderate drizzle" },
  { code: 55, text: "Dense drizzle" },
  { code: 56, text: "Light freezing drizzle" },
  { code: 57, text: "Dense freezing drizzle" },
  { code: 61, text: "Slight rain" },
  { code: 63, text: "Moderate rain" },
  { code: 65, text: "Heavy rain" },
  { code: 66, text: "Light freezing rain" },
  { code: 67, text: "Heavy freezing rain" },
  { code: 71, text: "Slight snow fall" },
  { code: 73, text: "Moderate snow fall" },
  { code: 75, text: "Heavy snow fall" },
  { code: 77, text: "Snow grains" },
  { code: 80, text: "Slight rain showers" },
  { code: 81, text: "Moderate rain showers" },
  { code: 82, text: "Violent rain showers" },
  { code: 85, text: "Slight snow showers" },
  { code: 86, text: "Heavy snow showers" },
  { code: 95, text: "Thunderstorm" },
  { code: 96, text: "Thunderstorm with slight hail" },
  { code: 99, text: "Thunderstorm with heavy hail" },
];
